name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Install ...
        2. Configure ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: PulseKit version
      placeholder: e.g. 0.1.0
    validations:
      required: true
  - type: input
    id: next-version
    attributes:
      label: Next.js version
      placeholder: e.g. 15.5.0
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      placeholder: e.g. 20.11.0
